# Generated by Django 4.2.29 on 2026-03-04 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Obstetrics & Gynecology, Cardiology, Dermatology', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this medical specialty.', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(blank=True, help_text='City where the doctor practices (for location search).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_address',
            field=models.TextField(blank=True, help_text='Full address of the clinic or hospital.', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_name',
            field=models.CharField(blank=True, help_text='Name of the hospital or clinic (e.g., Calapan Medical Center).', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Symptom or condition name (e.g., Headache, Chest Pain).', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this symptom or condition.', null=True)),
                ('specializations', models.ManyToManyField(help_text='Medical specializations related to this symptom.', related_name='symptoms', to='appointments.specialization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization_category',
            field=models.ForeignKey(blank=True, help_text='Link to the formal specialization category for search.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='appointments.specialization'),
        ),
    ]
