# Generated by Django 4.2.29 on 2026-03-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_specialization_doctor_city_doctor_clinic_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Pediatrics', 'Pediatrics'), ('Obstetrics & Gynecology (OB-GYN)', 'Obstetrics & Gynecology (OB-GYN)')], default='Pediatrics', help_text='Select specialization: Pediatrics or OB-GYN.', max_length=100),
        ),
    ]
