# Generated by Django 4.2.29 on 2026-03-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_hospital_remove_availability_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Google Maps embed src URL (from Share → Embed a map → copy the src value only)', null=True),
        ),
    ]
