# Generated by Django 4.2.29 on 2026-03-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_increase_coord_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Pediatrics', 'Pediatrics'), ('Obstetrics and Gynecology', 'Obstetrics and Gynecology'), ('Dentistry', 'Dentistry')], default='Pediatrics', max_length=100),
        ),
    ]
