# Generated by Django 4.2.29 on 2026-03-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='board_certification',
            field=models.FileField(blank=True, help_text='Board Certification (PDF, JPG, PNG).', null=True, upload_to='doctor_docs/board_cert/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='government_id_doc',
            field=models.FileField(blank=True, help_text='Government ID (PDF, JPG, PNG).', null=True, upload_to='doctor_docs/government_id/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_certificate',
            field=models.FileField(blank=True, help_text='Medical License Certificate (PDF, JPG, PNG).', null=True, upload_to='doctor_docs/license/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='medical_school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='professional_id_doc',
            field=models.FileField(blank=True, help_text='Professional ID (PDF, JPG, PNG).', null=True, upload_to='doctor_docs/professional_id/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='year_graduated',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
