# Generated by Django 4.2.29 on 2026-03-07 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='availability',
            name='accepting_status',
            field=models.CharField(choices=[('accepting', 'Accepting Patients'), ('paused', 'Paused')], default='accepting', help_text='Pause to temporarily stop accepting patients at this location.', max_length=10),
        ),
        migrations.AddField(
            model_name='availability',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text="Location for this slot (leave blank to inherit doctor's primary clinic).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availabilities', to='appointments.hospital'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL (e.g. https://www.linkedin.com/in/yourname)', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('appointment_booked', 'Appointment Booked'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_done', 'Appointment Completed'), ('doctor_approved', 'Doctor Approved'), ('doctor_revoked', 'Doctor Approval Revoked'), ('payment_received', 'Payment Received'), ('queue_update', 'Queue Update'), ('general', 'General')], default='general', max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('doctor', 'hospital', 'date', 'start_time', 'end_time')},
        ),
    ]
