# Generated by Django 4.2.30 on 2026-05-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_google_calendar_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Professional profile picture for credibility and recognition', null=True, upload_to='doctor_profiles/'),
        ),
    ]
