# Generated by Django 4.2.30 on 2026-05-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_doctor_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='jitsi_meet_link',
            field=models.URLField(blank=True, help_text='Jitsi Meet link for the online video consultation', null=True),
        ),
    ]
