# Generated by Django 4.2.30 on 2026-05-16 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_doctor_accepts_online_consultations'),
    ]

    operations = [
        migrations.CreateModel(
            name='JitsiLinkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jitsi_room_name', models.CharField(help_text='Jitsi room name (e.g., okidoki-5-12-42-a7c3d9e2)', max_length=255)),
                ('jitsi_url', models.URLField(help_text='Full Jitsi Meet URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link_accessed_count', models.PositiveIntegerField(default=0, help_text='Number of times the link has been accessed')),
                ('doctor_accessed_at', models.DateTimeField(blank=True, help_text='Timestamp when doctor first accessed the link', null=True)),
                ('patient_accessed_at', models.DateTimeField(blank=True, help_text='Timestamp when patient first accessed the link', null=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jitsi_link_log', to='appointments.appointment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
