# Generated by Django 4.2.30 on 2026-05-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_jitsilinklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='google_calendar_event_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='google_meet_link',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='google_calendar_token',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='is_google_calendar_connected',
        ),
        migrations.AddField(
            model_name='availability',
            name='location_name',
            field=models.CharField(blank=True, help_text='Enter a custom clinic/location name if not selecting from the dropdown above.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_online_consultation',
            field=models.BooleanField(default=False, help_text='Whether this is an online consultation via Jitsi Meet'),
        ),
    ]
