# Generated by Django 4.2.29 on 2026-03-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_hospital_map_embed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS latitude (e.g. 13.4115)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS longitude (e.g. 121.1804)', max_digits=12, null=True),
        ),
    ]
