# Generated by Django 4.2.30 on 2026-05-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_appointment_jitsi_meet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='accepts_online_consultations',
            field=models.BooleanField(default=True, help_text='Whether the doctor accepts online video consultations via Jitsi Meet'),
        ),
    ]
